name: Android Build Workflow

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Install Android SDK and NDK
        run: |
          mkdir /home/runner/android && cd /home/runner/android

          sudo apt install -y unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-11076708_latest.zip
          export PATH=$PATH:/home/runner/android/
          export PATH=$PATH:/home/runner/android/cmdline-tools/bin/

          yes | sdkmanager --sdk_root=/home/runner/android "platforms;android-34" "build-tools;34.0.0" "ndk;26.1.10909125" "cmake;3.31.0"

          echo "ANDROID_SDK_HOME=/home/runner/android" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=/home/runner/android/ndk/26.1.10909125" >> $GITHUB_ENV

          export PATH=$PATH:/home/runner/android/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/

      - name: Grant execute permission for gradlew
        run: chmod +x ./client/Android/Studio/gradlew

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Create local.properties
        run: echo "ndk.dir=/home/runner/android/ndk/26.1.10909125" > local.properties

      - name: Build with Gradle
        run: |
          cd ./client/Android/Studio
          ./gradlew assembleDebug
